/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { customFetch } from "./lib/custom-fetch";
export type BacktestCreateStartingBalance = number | string;

export interface BacktestCreate {
  strategy_id: string;
  /**
   * @minLength 1
   * @maxLength 10
   */
  symbol: string;
  starting_balance: BacktestCreateStartingBalance;
  timeframe: Timeframe;
  start_date: string;
  end_date: string;
}

export type BacktestDetailResponseMetrics = BacktestMetrics | null;

export interface BacktestDetailResponse {
  backtest_id: string;
  strategy_id: string;
  symbol: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  starting_balance: string;
  status: BacktestStatus;
  created_at: string;
  metrics: BacktestDetailResponseMetrics;
}

export interface BacktestMetrics {
  realised_pnl: number;
  unrealised_pnl: number;
  total_return: number;
  sharpe_ratio: number;
  max_drawdown: number;
  total_trades: number;
}

export interface BacktestResponse {
  backtest_id: string;
  strategy_id: string;
  symbol: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  starting_balance: string;
  status: BacktestStatus;
  created_at: string;
}

export type BacktestStatus =
  (typeof BacktestStatus)[keyof typeof BacktestStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BacktestStatus = {
  pending: "pending",
  in_progress: "in_progress",
  completed: "completed",
  failed: "failed",
} as const;

export type BacktestUpdateStatus = BacktestStatus | null;

export type BacktestUpdateMetricsAnyOf = { [key: string]: unknown };

export type BacktestUpdateMetrics = BacktestUpdateMetricsAnyOf | null;

export interface BacktestUpdate {
  status?: BacktestUpdateStatus;
  metrics?: BacktestUpdateMetrics;
}

export interface ContactForm {
  name: string;
  email: string;
  message: string;
}

export type DeployStrategyRequestStartingBalance = number | string;

export type DeployStrategyRequestConfigAnyOf = { [key: string]: unknown };

export type DeployStrategyRequestConfig =
  DeployStrategyRequestConfigAnyOf | null;

/**
 * Request model for deploying a strategy.
 */
export interface DeployStrategyRequest {
  broker_connection_id: string;
  /**
   * @minLength 1
   * @maxLength 10
   */
  ticker: string;
  /**
   * @minLength 1
   * @maxLength 10
   */
  timeframe: string;
  starting_balance: DeployStrategyRequestStartingBalance;
  config?: DeployStrategyRequestConfig;
}

export type DeploymentResponseConfigAnyOf = { [key: string]: unknown };

export type DeploymentResponseConfig = DeploymentResponseConfigAnyOf | null;

export type DeploymentResponseErrorMessage = string | null;

export type DeploymentResponseStoppedAt = string | null;

/**
 * Response model for deployment details.
 */
export interface DeploymentResponse {
  deployment_id: string;
  strategy_id: string;
  broker_connection_id: string;
  ticker: string;
  timeframe: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  starting_balance: string;
  status: StrategyDeploymentStatus;
  config: DeploymentResponseConfig;
  error_message: DeploymentResponseErrorMessage;
  created_at: string;
  updated_at: string;
  stopped_at: DeploymentResponseStoppedAt;
}

export interface GetOauthUrlResponse {
  url: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type OrderResponseInputQuantity = number | string;

export type OrderResponseInputFilledQuantity = number | string;

export type OrderResponseInputLimitPrice = number | string | null;

export type OrderResponseInputStopPrice = number | string | null;

export type OrderResponseInputAverageFillPrice = number | string | null;

export type OrderResponseInputFilledAt = string | null;

export type OrderResponseInputClientOrderId = string | null;

export type OrderResponseInputBrokerOrderId = string | null;

export interface OrderResponseInput {
  order_id: string;
  symbol: string;
  side: string;
  order_type: string;
  quantity: OrderResponseInputQuantity;
  filled_quantity: OrderResponseInputFilledQuantity;
  limit_price: OrderResponseInputLimitPrice;
  stop_price: OrderResponseInputStopPrice;
  average_fill_price: OrderResponseInputAverageFillPrice;
  status: string;
  time_in_force: string;
  submitted_at: string;
  filled_at: OrderResponseInputFilledAt;
  client_order_id: OrderResponseInputClientOrderId;
  broker_order_id: OrderResponseInputBrokerOrderId;
}

export type OrderResponseOutputLimitPrice = string | null;

export type OrderResponseOutputStopPrice = string | null;

export type OrderResponseOutputAverageFillPrice = string | null;

export type OrderResponseOutputFilledAt = string | null;

export type OrderResponseOutputClientOrderId = string | null;

export type OrderResponseOutputBrokerOrderId = string | null;

export interface OrderResponseOutput {
  order_id: string;
  symbol: string;
  side: string;
  order_type: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  quantity: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  filled_quantity: string;
  limit_price: OrderResponseOutputLimitPrice;
  stop_price: OrderResponseOutputStopPrice;
  average_fill_price: OrderResponseOutputAverageFillPrice;
  status: string;
  time_in_force: string;
  submitted_at: string;
  filled_at: OrderResponseOutputFilledAt;
  client_order_id: OrderResponseOutputClientOrderId;
  broker_order_id: OrderResponseOutputBrokerOrderId;
}

export type PricingTierType =
  (typeof PricingTierType)[keyof typeof PricingTierType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PricingTierType = {
  free: "free",
  pro: "pro",
  enterprise: "enterprise",
} as const;

export type StrategyCreateDescription = string | null;

export interface StrategyCreate {
  /**
   * @minLength 1
   * @maxLength 20
   */
  name: string;
  description?: StrategyCreateDescription;
  prompt: string;
}

export type StrategyDeploymentStatus =
  (typeof StrategyDeploymentStatus)[keyof typeof StrategyDeploymentStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StrategyDeploymentStatus = {
  pending: "pending",
  running: "running",
  error: "error",
  stopped: "stopped",
} as const;

export type StrategyDetailResponseDescription = string | null;

export interface StrategyDetailResponse {
  strategy_id: string;
  name: string;
  description: StrategyDetailResponseDescription;
  created_at: string;
  updated_at: string;
  code: string;
}

export type StrategyMetricsEquityCurveItemItem1 = number | string;

export interface StrategyMetrics {
  realised_pnl: number;
  unrealised_pnl: number;
  total_return: number;
  sharpe_ratio: number;
  max_drawdown: number;
  equity_curve: [string, StrategyMetricsEquityCurveItemItem1][];
}

export type StrategyResponseDescription = string | null;

export interface StrategyResponse {
  strategy_id: string;
  name: string;
  description: StrategyResponseDescription;
  created_at: string;
  updated_at: string;
}

export type StrategySummaryResponseDescription = string | null;

export interface StrategySummaryResponse {
  strategy_id: string;
  name: string;
  description: StrategySummaryResponseDescription;
  created_at: string;
  updated_at: string;
  metrics: StrategyMetrics;
}

export type StrategyUpdateName = string | null;

export type StrategyUpdateDescription = string | null;

export interface StrategyUpdate {
  name?: StrategyUpdateName;
  description?: StrategyUpdateDescription;
}

/**
 * Supported timeframes for OHLC data.
 */
export type Timeframe = (typeof Timeframe)[keyof typeof Timeframe];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Timeframe = {
  "1m": "1m",
  "5m": "5m",
  "15m": "15m",
  "30m": "30m",
  "1h": "1h",
  "1d": "1d",
} as const;

export interface UpdateEmail {
  email: string;
}

export interface UpdatePassword {
  password: string;
}

export interface UpdateUsername {
  username: string;
}

export interface UserCreate {
  password: string;
  username: string;
  email: string;
}

export type UserLoginUsername = string | null;

export type UserLoginEmail = string | null;

export interface UserLogin {
  username?: UserLoginUsername;
  email?: UserLoginEmail;
  password: string;
}

export interface UserMe {
  username: string;
  pricing_tier: PricingTierType;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type VerifyActionAction =
  (typeof VerifyActionAction)[keyof typeof VerifyActionAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VerifyActionAction = {
  change_username: "change_username",
  change_password: "change_password",
  change_email: "change_email",
} as const;

export interface VerifyAction {
  code: string;
  action: VerifyActionAction;
}

export interface VerifyCode {
  code: string;
}

export type ListBacktestsEndpointBacktestsGetParams = {
  /**
   * @minimum 0
   */
  skip?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
};

export type GetBacktestOrdersEndpointBacktestsBacktestIdOrdersGetParams = {
  /**
   * @minimum 0
   */
  skip?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
};

export type OauthCallbackBrokersAlpacaOauthCallbackGetParams = {
  code?: string | null;
  state?: string | null;
  error?: string | null;
};

export type ListStrategyDeploymentsEndpointDeploymentsStrategiesStrategyIdDeploymentsGetParams =
  {
    /**
     * @minimum 0
     */
    skip?: number;
    /**
     * @minimum 1
     * @maximum 100
     */
    limit?: number;
  };

export type ListAllDeploymentsEndpointDeploymentsGetParams = {
  /**
   * @minimum 0
   */
  skip?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  status?: StrategyDeploymentStatus | null;
};

export type ListStrategiesEndpointStrategiesGetParams = {
  /**
   * @minimum 0
   */
  skip?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
};

export type ListStrategySummariesEndpointStrategiesSummariesGetParams = {
  /**
   * @minimum 0
   */
  skip?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
};

/**
 * @summary Register
 */
export type registerAuthRegisterPostResponse200 = {
  data: unknown;
  status: 200;
};

export type registerAuthRegisterPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type registerAuthRegisterPostResponseSuccess =
  registerAuthRegisterPostResponse200 & {
    headers: Headers;
  };
export type registerAuthRegisterPostResponseError =
  registerAuthRegisterPostResponse422 & {
    headers: Headers;
  };

export type registerAuthRegisterPostResponse =
  | registerAuthRegisterPostResponseSuccess
  | registerAuthRegisterPostResponseError;

export const getRegisterAuthRegisterPostUrl = () => {
  return `/auth/register`;
};

export const registerAuthRegisterPost = async (
  userCreate: UserCreate,
  options?: RequestInit,
): Promise<registerAuthRegisterPostResponse> => {
  return customFetch<registerAuthRegisterPostResponse>(
    getRegisterAuthRegisterPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(userCreate),
    },
  );
};

/**
 * @summary Login
 */
export type loginAuthLoginPostResponse200 = {
  data: unknown;
  status: 200;
};

export type loginAuthLoginPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type loginAuthLoginPostResponseSuccess =
  loginAuthLoginPostResponse200 & {
    headers: Headers;
  };
export type loginAuthLoginPostResponseError = loginAuthLoginPostResponse422 & {
  headers: Headers;
};

export type loginAuthLoginPostResponse =
  | loginAuthLoginPostResponseSuccess
  | loginAuthLoginPostResponseError;

export const getLoginAuthLoginPostUrl = () => {
  return `/auth/login`;
};

export const loginAuthLoginPost = async (
  userLogin: UserLogin,
  options?: RequestInit,
): Promise<loginAuthLoginPostResponse> => {
  return customFetch<loginAuthLoginPostResponse>(getLoginAuthLoginPostUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(userLogin),
  });
};

/**
 * @summary Request Email Verification
 */
export type requestEmailVerificationAuthRequestEmailVerificationPostResponse200 =
  {
    data: unknown;
    status: 200;
  };

export type requestEmailVerificationAuthRequestEmailVerificationPostResponseSuccess =
  requestEmailVerificationAuthRequestEmailVerificationPostResponse200 & {
    headers: Headers;
  };
export type requestEmailVerificationAuthRequestEmailVerificationPostResponse =
  requestEmailVerificationAuthRequestEmailVerificationPostResponseSuccess;

export const getRequestEmailVerificationAuthRequestEmailVerificationPostUrl =
  () => {
    return `/auth/request-email-verification`;
  };

export const requestEmailVerificationAuthRequestEmailVerificationPost = async (
  options?: RequestInit,
): Promise<requestEmailVerificationAuthRequestEmailVerificationPostResponse> => {
  return customFetch<requestEmailVerificationAuthRequestEmailVerificationPostResponse>(
    getRequestEmailVerificationAuthRequestEmailVerificationPostUrl(),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Verify Email
 */
export type verifyEmailAuthVerifyEmailPostResponse200 = {
  data: unknown;
  status: 200;
};

export type verifyEmailAuthVerifyEmailPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type verifyEmailAuthVerifyEmailPostResponseSuccess =
  verifyEmailAuthVerifyEmailPostResponse200 & {
    headers: Headers;
  };
export type verifyEmailAuthVerifyEmailPostResponseError =
  verifyEmailAuthVerifyEmailPostResponse422 & {
    headers: Headers;
  };

export type verifyEmailAuthVerifyEmailPostResponse =
  | verifyEmailAuthVerifyEmailPostResponseSuccess
  | verifyEmailAuthVerifyEmailPostResponseError;

export const getVerifyEmailAuthVerifyEmailPostUrl = () => {
  return `/auth/verify-email`;
};

export const verifyEmailAuthVerifyEmailPost = async (
  verifyCode: VerifyCode,
  options?: RequestInit,
): Promise<verifyEmailAuthVerifyEmailPostResponse> => {
  return customFetch<verifyEmailAuthVerifyEmailPostResponse>(
    getVerifyEmailAuthVerifyEmailPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(verifyCode),
    },
  );
};

/**
 * @summary Logout
 */
export type logoutAuthLogoutPostResponse200 = {
  data: unknown;
  status: 200;
};

export type logoutAuthLogoutPostResponseSuccess =
  logoutAuthLogoutPostResponse200 & {
    headers: Headers;
  };
export type logoutAuthLogoutPostResponse = logoutAuthLogoutPostResponseSuccess;

export const getLogoutAuthLogoutPostUrl = () => {
  return `/auth/logout`;
};

export const logoutAuthLogoutPost = async (
  options?: RequestInit,
): Promise<logoutAuthLogoutPostResponse> => {
  return customFetch<logoutAuthLogoutPostResponse>(
    getLogoutAuthLogoutPostUrl(),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Get Me
 */
export type getMeAuthMeGetResponse200 = {
  data: UserMe;
  status: 200;
};

export type getMeAuthMeGetResponseSuccess = getMeAuthMeGetResponse200 & {
  headers: Headers;
};
export type getMeAuthMeGetResponse = getMeAuthMeGetResponseSuccess;

export const getGetMeAuthMeGetUrl = () => {
  return `/auth/me`;
};

export const getMeAuthMeGet = async (
  options?: RequestInit,
): Promise<getMeAuthMeGetResponse> => {
  return customFetch<getMeAuthMeGetResponse>(getGetMeAuthMeGetUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Change Username
 */
export type changeUsernameAuthChangeUsernamePostResponse202 = {
  data: unknown;
  status: 202;
};

export type changeUsernameAuthChangeUsernamePostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type changeUsernameAuthChangeUsernamePostResponseSuccess =
  changeUsernameAuthChangeUsernamePostResponse202 & {
    headers: Headers;
  };
export type changeUsernameAuthChangeUsernamePostResponseError =
  changeUsernameAuthChangeUsernamePostResponse422 & {
    headers: Headers;
  };

export type changeUsernameAuthChangeUsernamePostResponse =
  | changeUsernameAuthChangeUsernamePostResponseSuccess
  | changeUsernameAuthChangeUsernamePostResponseError;

export const getChangeUsernameAuthChangeUsernamePostUrl = () => {
  return `/auth/change-username`;
};

export const changeUsernameAuthChangeUsernamePost = async (
  updateUsername: UpdateUsername,
  options?: RequestInit,
): Promise<changeUsernameAuthChangeUsernamePostResponse> => {
  return customFetch<changeUsernameAuthChangeUsernamePostResponse>(
    getChangeUsernameAuthChangeUsernamePostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateUsername),
    },
  );
};

/**
 * @summary Change Password
 */
export type changePasswordAuthChangePasswordPostResponse202 = {
  data: unknown;
  status: 202;
};

export type changePasswordAuthChangePasswordPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type changePasswordAuthChangePasswordPostResponseSuccess =
  changePasswordAuthChangePasswordPostResponse202 & {
    headers: Headers;
  };
export type changePasswordAuthChangePasswordPostResponseError =
  changePasswordAuthChangePasswordPostResponse422 & {
    headers: Headers;
  };

export type changePasswordAuthChangePasswordPostResponse =
  | changePasswordAuthChangePasswordPostResponseSuccess
  | changePasswordAuthChangePasswordPostResponseError;

export const getChangePasswordAuthChangePasswordPostUrl = () => {
  return `/auth/change-password`;
};

export const changePasswordAuthChangePasswordPost = async (
  updatePassword: UpdatePassword,
  options?: RequestInit,
): Promise<changePasswordAuthChangePasswordPostResponse> => {
  return customFetch<changePasswordAuthChangePasswordPostResponse>(
    getChangePasswordAuthChangePasswordPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updatePassword),
    },
  );
};

/**
 * @summary Change Email
 */
export type changeEmailAuthChangeEmailPostResponse202 = {
  data: unknown;
  status: 202;
};

export type changeEmailAuthChangeEmailPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type changeEmailAuthChangeEmailPostResponseSuccess =
  changeEmailAuthChangeEmailPostResponse202 & {
    headers: Headers;
  };
export type changeEmailAuthChangeEmailPostResponseError =
  changeEmailAuthChangeEmailPostResponse422 & {
    headers: Headers;
  };

export type changeEmailAuthChangeEmailPostResponse =
  | changeEmailAuthChangeEmailPostResponseSuccess
  | changeEmailAuthChangeEmailPostResponseError;

export const getChangeEmailAuthChangeEmailPostUrl = () => {
  return `/auth/change-email`;
};

export const changeEmailAuthChangeEmailPost = async (
  updateEmail: UpdateEmail,
  options?: RequestInit,
): Promise<changeEmailAuthChangeEmailPostResponse> => {
  return customFetch<changeEmailAuthChangeEmailPostResponse>(
    getChangeEmailAuthChangeEmailPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateEmail),
    },
  );
};

/**
 * @summary Verify Action
 */
export type verifyActionAuthVerifyActionPostResponse200 = {
  data: unknown;
  status: 200;
};

export type verifyActionAuthVerifyActionPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type verifyActionAuthVerifyActionPostResponseSuccess =
  verifyActionAuthVerifyActionPostResponse200 & {
    headers: Headers;
  };
export type verifyActionAuthVerifyActionPostResponseError =
  verifyActionAuthVerifyActionPostResponse422 & {
    headers: Headers;
  };

export type verifyActionAuthVerifyActionPostResponse =
  | verifyActionAuthVerifyActionPostResponseSuccess
  | verifyActionAuthVerifyActionPostResponseError;

export const getVerifyActionAuthVerifyActionPostUrl = () => {
  return `/auth/verify-action`;
};

export const verifyActionAuthVerifyActionPost = async (
  verifyAction: VerifyAction,
  options?: RequestInit,
): Promise<verifyActionAuthVerifyActionPostResponse> => {
  return customFetch<verifyActionAuthVerifyActionPostResponse>(
    getVerifyActionAuthVerifyActionPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(verifyAction),
    },
  );
};

/**
 * Create a new backtest.
 * @summary Create Backtest Endpoint
 */
export type createBacktestEndpointBacktestsPostResponse201 = {
  data: BacktestResponse;
  status: 201;
};

export type createBacktestEndpointBacktestsPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createBacktestEndpointBacktestsPostResponseSuccess =
  createBacktestEndpointBacktestsPostResponse201 & {
    headers: Headers;
  };
export type createBacktestEndpointBacktestsPostResponseError =
  createBacktestEndpointBacktestsPostResponse422 & {
    headers: Headers;
  };

export type createBacktestEndpointBacktestsPostResponse =
  | createBacktestEndpointBacktestsPostResponseSuccess
  | createBacktestEndpointBacktestsPostResponseError;

export const getCreateBacktestEndpointBacktestsPostUrl = () => {
  return `/backtests/`;
};

export const createBacktestEndpointBacktestsPost = async (
  backtestCreate: BacktestCreate,
  options?: RequestInit,
): Promise<createBacktestEndpointBacktestsPostResponse> => {
  return customFetch<createBacktestEndpointBacktestsPostResponse>(
    getCreateBacktestEndpointBacktestsPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(backtestCreate),
    },
  );
};

/**
 * List all backtests with pagination.
 * @summary List Backtests Endpoint
 */
export type listBacktestsEndpointBacktestsGetResponse200 = {
  data: BacktestResponse[];
  status: 200;
};

export type listBacktestsEndpointBacktestsGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type listBacktestsEndpointBacktestsGetResponseSuccess =
  listBacktestsEndpointBacktestsGetResponse200 & {
    headers: Headers;
  };
export type listBacktestsEndpointBacktestsGetResponseError =
  listBacktestsEndpointBacktestsGetResponse422 & {
    headers: Headers;
  };

export type listBacktestsEndpointBacktestsGetResponse =
  | listBacktestsEndpointBacktestsGetResponseSuccess
  | listBacktestsEndpointBacktestsGetResponseError;

export const getListBacktestsEndpointBacktestsGetUrl = (
  params?: ListBacktestsEndpointBacktestsGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/backtests/?${stringifiedParams}`
    : `/backtests/`;
};

export const listBacktestsEndpointBacktestsGet = async (
  params?: ListBacktestsEndpointBacktestsGetParams,
  options?: RequestInit,
): Promise<listBacktestsEndpointBacktestsGetResponse> => {
  return customFetch<listBacktestsEndpointBacktestsGetResponse>(
    getListBacktestsEndpointBacktestsGetUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Get a backtest by ID with full details including metrics.
 * @summary Get Backtest Endpoint
 */
export type getBacktestEndpointBacktestsBacktestIdGetResponse200 = {
  data: BacktestDetailResponse;
  status: 200;
};

export type getBacktestEndpointBacktestsBacktestIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getBacktestEndpointBacktestsBacktestIdGetResponseSuccess =
  getBacktestEndpointBacktestsBacktestIdGetResponse200 & {
    headers: Headers;
  };
export type getBacktestEndpointBacktestsBacktestIdGetResponseError =
  getBacktestEndpointBacktestsBacktestIdGetResponse422 & {
    headers: Headers;
  };

export type getBacktestEndpointBacktestsBacktestIdGetResponse =
  | getBacktestEndpointBacktestsBacktestIdGetResponseSuccess
  | getBacktestEndpointBacktestsBacktestIdGetResponseError;

export const getGetBacktestEndpointBacktestsBacktestIdGetUrl = (
  backtestId: string,
) => {
  return `/backtests/${backtestId}`;
};

export const getBacktestEndpointBacktestsBacktestIdGet = async (
  backtestId: string,
  options?: RequestInit,
): Promise<getBacktestEndpointBacktestsBacktestIdGetResponse> => {
  return customFetch<getBacktestEndpointBacktestsBacktestIdGetResponse>(
    getGetBacktestEndpointBacktestsBacktestIdGetUrl(backtestId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Update a backtest (status and/or metrics).
 * @summary Update Backtest Endpoint
 */
export type updateBacktestEndpointBacktestsBacktestIdPatchResponse200 = {
  data: BacktestResponse;
  status: 200;
};

export type updateBacktestEndpointBacktestsBacktestIdPatchResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type updateBacktestEndpointBacktestsBacktestIdPatchResponseSuccess =
  updateBacktestEndpointBacktestsBacktestIdPatchResponse200 & {
    headers: Headers;
  };
export type updateBacktestEndpointBacktestsBacktestIdPatchResponseError =
  updateBacktestEndpointBacktestsBacktestIdPatchResponse422 & {
    headers: Headers;
  };

export type updateBacktestEndpointBacktestsBacktestIdPatchResponse =
  | updateBacktestEndpointBacktestsBacktestIdPatchResponseSuccess
  | updateBacktestEndpointBacktestsBacktestIdPatchResponseError;

export const getUpdateBacktestEndpointBacktestsBacktestIdPatchUrl = (
  backtestId: string,
) => {
  return `/backtests/${backtestId}`;
};

export const updateBacktestEndpointBacktestsBacktestIdPatch = async (
  backtestId: string,
  backtestUpdate: BacktestUpdate,
  options?: RequestInit,
): Promise<updateBacktestEndpointBacktestsBacktestIdPatchResponse> => {
  return customFetch<updateBacktestEndpointBacktestsBacktestIdPatchResponse>(
    getUpdateBacktestEndpointBacktestsBacktestIdPatchUrl(backtestId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(backtestUpdate),
    },
  );
};

/**
 * Delete a backtest.
 * @summary Delete Backtest Endpoint
 */
export type deleteBacktestEndpointBacktestsBacktestIdDeleteResponse204 = {
  data: void;
  status: 204;
};

export type deleteBacktestEndpointBacktestsBacktestIdDeleteResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type deleteBacktestEndpointBacktestsBacktestIdDeleteResponseSuccess =
  deleteBacktestEndpointBacktestsBacktestIdDeleteResponse204 & {
    headers: Headers;
  };
export type deleteBacktestEndpointBacktestsBacktestIdDeleteResponseError =
  deleteBacktestEndpointBacktestsBacktestIdDeleteResponse422 & {
    headers: Headers;
  };

export type deleteBacktestEndpointBacktestsBacktestIdDeleteResponse =
  | deleteBacktestEndpointBacktestsBacktestIdDeleteResponseSuccess
  | deleteBacktestEndpointBacktestsBacktestIdDeleteResponseError;

export const getDeleteBacktestEndpointBacktestsBacktestIdDeleteUrl = (
  backtestId: string,
) => {
  return `/backtests/${backtestId}`;
};

export const deleteBacktestEndpointBacktestsBacktestIdDelete = async (
  backtestId: string,
  options?: RequestInit,
): Promise<deleteBacktestEndpointBacktestsBacktestIdDeleteResponse> => {
  return customFetch<deleteBacktestEndpointBacktestsBacktestIdDeleteResponse>(
    getDeleteBacktestEndpointBacktestsBacktestIdDeleteUrl(backtestId),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * Get all orders/trades for a backtest with pagination.
 * @summary Get Backtest Orders Endpoint
 */
export type getBacktestOrdersEndpointBacktestsBacktestIdOrdersGetResponse200 = {
  data: OrderResponseOutput[];
  status: 200;
};

export type getBacktestOrdersEndpointBacktestsBacktestIdOrdersGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getBacktestOrdersEndpointBacktestsBacktestIdOrdersGetResponseSuccess =
  getBacktestOrdersEndpointBacktestsBacktestIdOrdersGetResponse200 & {
    headers: Headers;
  };
export type getBacktestOrdersEndpointBacktestsBacktestIdOrdersGetResponseError =
  getBacktestOrdersEndpointBacktestsBacktestIdOrdersGetResponse422 & {
    headers: Headers;
  };

export type getBacktestOrdersEndpointBacktestsBacktestIdOrdersGetResponse =
  | getBacktestOrdersEndpointBacktestsBacktestIdOrdersGetResponseSuccess
  | getBacktestOrdersEndpointBacktestsBacktestIdOrdersGetResponseError;

export const getGetBacktestOrdersEndpointBacktestsBacktestIdOrdersGetUrl = (
  backtestId: string,
  params?: GetBacktestOrdersEndpointBacktestsBacktestIdOrdersGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/backtests/${backtestId}/orders?${stringifiedParams}`
    : `/backtests/${backtestId}/orders`;
};

export const getBacktestOrdersEndpointBacktestsBacktestIdOrdersGet = async (
  backtestId: string,
  params?: GetBacktestOrdersEndpointBacktestsBacktestIdOrdersGetParams,
  options?: RequestInit,
): Promise<getBacktestOrdersEndpointBacktestsBacktestIdOrdersGetResponse> => {
  return customFetch<getBacktestOrdersEndpointBacktestsBacktestIdOrdersGetResponse>(
    getGetBacktestOrdersEndpointBacktestsBacktestIdOrdersGetUrl(
      backtestId,
      params,
    ),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get Oauth Url
 */
export type getOauthUrlBrokersAlpacaOauthGetResponse200 = {
  data: GetOauthUrlResponse;
  status: 200;
};

export type getOauthUrlBrokersAlpacaOauthGetResponseSuccess =
  getOauthUrlBrokersAlpacaOauthGetResponse200 & {
    headers: Headers;
  };
export type getOauthUrlBrokersAlpacaOauthGetResponse =
  getOauthUrlBrokersAlpacaOauthGetResponseSuccess;

export const getGetOauthUrlBrokersAlpacaOauthGetUrl = () => {
  return `/brokers/alpaca/oauth`;
};

export const getOauthUrlBrokersAlpacaOauthGet = async (
  options?: RequestInit,
): Promise<getOauthUrlBrokersAlpacaOauthGetResponse> => {
  return customFetch<getOauthUrlBrokersAlpacaOauthGetResponse>(
    getGetOauthUrlBrokersAlpacaOauthGetUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Oauth Callback
 */
export type oauthCallbackBrokersAlpacaOauthCallbackGetResponse200 = {
  data: unknown;
  status: 200;
};

export type oauthCallbackBrokersAlpacaOauthCallbackGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type oauthCallbackBrokersAlpacaOauthCallbackGetResponseSuccess =
  oauthCallbackBrokersAlpacaOauthCallbackGetResponse200 & {
    headers: Headers;
  };
export type oauthCallbackBrokersAlpacaOauthCallbackGetResponseError =
  oauthCallbackBrokersAlpacaOauthCallbackGetResponse422 & {
    headers: Headers;
  };

export type oauthCallbackBrokersAlpacaOauthCallbackGetResponse =
  | oauthCallbackBrokersAlpacaOauthCallbackGetResponseSuccess
  | oauthCallbackBrokersAlpacaOauthCallbackGetResponseError;

export const getOauthCallbackBrokersAlpacaOauthCallbackGetUrl = (
  params?: OauthCallbackBrokersAlpacaOauthCallbackGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/brokers/alpaca/oauth/callback?${stringifiedParams}`
    : `/brokers/alpaca/oauth/callback`;
};

export const oauthCallbackBrokersAlpacaOauthCallbackGet = async (
  params?: OauthCallbackBrokersAlpacaOauthCallbackGetParams,
  options?: RequestInit,
): Promise<oauthCallbackBrokersAlpacaOauthCallbackGetResponse> => {
  return customFetch<oauthCallbackBrokersAlpacaOauthCallbackGetResponse>(
    getOauthCallbackBrokersAlpacaOauthCallbackGetUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Deploy a strategy to a broker connection.

Creates a new deployment that will run the specified strategy
with the given configuration on the connected broker account.
 * @summary Deploy Strategy Endpoint
 */
export type deployStrategyEndpointDeploymentsStrategiesStrategyIdDeployPostResponse201 =
  {
    data: DeploymentResponse;
    status: 201;
  };

export type deployStrategyEndpointDeploymentsStrategiesStrategyIdDeployPostResponse422 =
  {
    data: HTTPValidationError;
    status: 422;
  };

export type deployStrategyEndpointDeploymentsStrategiesStrategyIdDeployPostResponseSuccess =
  deployStrategyEndpointDeploymentsStrategiesStrategyIdDeployPostResponse201 & {
    headers: Headers;
  };
export type deployStrategyEndpointDeploymentsStrategiesStrategyIdDeployPostResponseError =
  deployStrategyEndpointDeploymentsStrategiesStrategyIdDeployPostResponse422 & {
    headers: Headers;
  };

export type deployStrategyEndpointDeploymentsStrategiesStrategyIdDeployPostResponse =

    | deployStrategyEndpointDeploymentsStrategiesStrategyIdDeployPostResponseSuccess
    | deployStrategyEndpointDeploymentsStrategiesStrategyIdDeployPostResponseError;

export const getDeployStrategyEndpointDeploymentsStrategiesStrategyIdDeployPostUrl =
  (strategyId: string) => {
    return `/deployments/strategies/${strategyId}/deploy`;
  };

export const deployStrategyEndpointDeploymentsStrategiesStrategyIdDeployPost =
  async (
    strategyId: string,
    deployStrategyRequest: DeployStrategyRequest,
    options?: RequestInit,
  ): Promise<deployStrategyEndpointDeploymentsStrategiesStrategyIdDeployPostResponse> => {
    return customFetch<deployStrategyEndpointDeploymentsStrategiesStrategyIdDeployPostResponse>(
      getDeployStrategyEndpointDeploymentsStrategiesStrategyIdDeployPostUrl(
        strategyId,
      ),
      {
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(deployStrategyRequest),
      },
    );
  };

/**
 * List all deployments for a specific strategy with pagination.

Returns list of deployments for the given strategy,
ordered by creation date (newest first).
 * @summary List Strategy Deployments Endpoint
 */
export type listStrategyDeploymentsEndpointDeploymentsStrategiesStrategyIdDeploymentsGetResponse200 =
  {
    data: DeploymentResponse[];
    status: 200;
  };

export type listStrategyDeploymentsEndpointDeploymentsStrategiesStrategyIdDeploymentsGetResponse422 =
  {
    data: HTTPValidationError;
    status: 422;
  };

export type listStrategyDeploymentsEndpointDeploymentsStrategiesStrategyIdDeploymentsGetResponseSuccess =
  listStrategyDeploymentsEndpointDeploymentsStrategiesStrategyIdDeploymentsGetResponse200 & {
    headers: Headers;
  };
export type listStrategyDeploymentsEndpointDeploymentsStrategiesStrategyIdDeploymentsGetResponseError =
  listStrategyDeploymentsEndpointDeploymentsStrategiesStrategyIdDeploymentsGetResponse422 & {
    headers: Headers;
  };

export type listStrategyDeploymentsEndpointDeploymentsStrategiesStrategyIdDeploymentsGetResponse =

    | listStrategyDeploymentsEndpointDeploymentsStrategiesStrategyIdDeploymentsGetResponseSuccess
    | listStrategyDeploymentsEndpointDeploymentsStrategiesStrategyIdDeploymentsGetResponseError;

export const getListStrategyDeploymentsEndpointDeploymentsStrategiesStrategyIdDeploymentsGetUrl =
  (
    strategyId: string,
    params?: ListStrategyDeploymentsEndpointDeploymentsStrategiesStrategyIdDeploymentsGetParams,
  ) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
      if (value !== undefined) {
        normalizedParams.append(
          key,
          value === null ? "null" : value.toString(),
        );
      }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
      ? `/deployments/strategies/${strategyId}/deployments?${stringifiedParams}`
      : `/deployments/strategies/${strategyId}/deployments`;
  };

export const listStrategyDeploymentsEndpointDeploymentsStrategiesStrategyIdDeploymentsGet =
  async (
    strategyId: string,
    params?: ListStrategyDeploymentsEndpointDeploymentsStrategiesStrategyIdDeploymentsGetParams,
    options?: RequestInit,
  ): Promise<listStrategyDeploymentsEndpointDeploymentsStrategiesStrategyIdDeploymentsGetResponse> => {
    return customFetch<listStrategyDeploymentsEndpointDeploymentsStrategiesStrategyIdDeploymentsGetResponse>(
      getListStrategyDeploymentsEndpointDeploymentsStrategiesStrategyIdDeploymentsGetUrl(
        strategyId,
        params,
      ),
      {
        ...options,
        method: "GET",
      },
    );
  };

/**
 * Get deployment details by ID.

Returns full details of a specific deployment including status,
configuration, and error messages if any.
 * @summary Get Deployment Endpoint
 */
export type getDeploymentEndpointDeploymentsDeploymentIdGetResponse200 = {
  data: DeploymentResponse;
  status: 200;
};

export type getDeploymentEndpointDeploymentsDeploymentIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getDeploymentEndpointDeploymentsDeploymentIdGetResponseSuccess =
  getDeploymentEndpointDeploymentsDeploymentIdGetResponse200 & {
    headers: Headers;
  };
export type getDeploymentEndpointDeploymentsDeploymentIdGetResponseError =
  getDeploymentEndpointDeploymentsDeploymentIdGetResponse422 & {
    headers: Headers;
  };

export type getDeploymentEndpointDeploymentsDeploymentIdGetResponse =
  | getDeploymentEndpointDeploymentsDeploymentIdGetResponseSuccess
  | getDeploymentEndpointDeploymentsDeploymentIdGetResponseError;

export const getGetDeploymentEndpointDeploymentsDeploymentIdGetUrl = (
  deploymentId: string,
) => {
  return `/deployments/${deploymentId}`;
};

export const getDeploymentEndpointDeploymentsDeploymentIdGet = async (
  deploymentId: string,
  options?: RequestInit,
): Promise<getDeploymentEndpointDeploymentsDeploymentIdGetResponse> => {
  return customFetch<getDeploymentEndpointDeploymentsDeploymentIdGetResponse>(
    getGetDeploymentEndpointDeploymentsDeploymentIdGetUrl(deploymentId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Stop a running deployment.

Updates deployment status and sets stopped_at timestamp.
Can only stop deployments that are currently RUNNING or PENDING.
 * @summary Stop Deployment Endpoint
 */
export type stopDeploymentEndpointDeploymentsDeploymentIdStopPostResponse200 = {
  data: DeploymentResponse;
  status: 200;
};

export type stopDeploymentEndpointDeploymentsDeploymentIdStopPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type stopDeploymentEndpointDeploymentsDeploymentIdStopPostResponseSuccess =
  stopDeploymentEndpointDeploymentsDeploymentIdStopPostResponse200 & {
    headers: Headers;
  };
export type stopDeploymentEndpointDeploymentsDeploymentIdStopPostResponseError =
  stopDeploymentEndpointDeploymentsDeploymentIdStopPostResponse422 & {
    headers: Headers;
  };

export type stopDeploymentEndpointDeploymentsDeploymentIdStopPostResponse =
  | stopDeploymentEndpointDeploymentsDeploymentIdStopPostResponseSuccess
  | stopDeploymentEndpointDeploymentsDeploymentIdStopPostResponseError;

export const getStopDeploymentEndpointDeploymentsDeploymentIdStopPostUrl = (
  deploymentId: string,
) => {
  return `/deployments/${deploymentId}/stop`;
};

export const stopDeploymentEndpointDeploymentsDeploymentIdStopPost = async (
  deploymentId: string,
  options?: RequestInit,
): Promise<stopDeploymentEndpointDeploymentsDeploymentIdStopPostResponse> => {
  return customFetch<stopDeploymentEndpointDeploymentsDeploymentIdStopPostResponse>(
    getStopDeploymentEndpointDeploymentsDeploymentIdStopPostUrl(deploymentId),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * List all user's deployments with pagination and optional status filter.

Returns list of all deployments belonging to the user,
optionally filtered by status, ordered by creation date (newest first).
 * @summary List All Deployments Endpoint
 */
export type listAllDeploymentsEndpointDeploymentsGetResponse200 = {
  data: DeploymentResponse[];
  status: 200;
};

export type listAllDeploymentsEndpointDeploymentsGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type listAllDeploymentsEndpointDeploymentsGetResponseSuccess =
  listAllDeploymentsEndpointDeploymentsGetResponse200 & {
    headers: Headers;
  };
export type listAllDeploymentsEndpointDeploymentsGetResponseError =
  listAllDeploymentsEndpointDeploymentsGetResponse422 & {
    headers: Headers;
  };

export type listAllDeploymentsEndpointDeploymentsGetResponse =
  | listAllDeploymentsEndpointDeploymentsGetResponseSuccess
  | listAllDeploymentsEndpointDeploymentsGetResponseError;

export const getListAllDeploymentsEndpointDeploymentsGetUrl = (
  params?: ListAllDeploymentsEndpointDeploymentsGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/deployments/?${stringifiedParams}`
    : `/deployments/`;
};

export const listAllDeploymentsEndpointDeploymentsGet = async (
  params?: ListAllDeploymentsEndpointDeploymentsGetParams,
  options?: RequestInit,
): Promise<listAllDeploymentsEndpointDeploymentsGetResponse> => {
  return customFetch<listAllDeploymentsEndpointDeploymentsGetResponse>(
    getListAllDeploymentsEndpointDeploymentsGetUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Contact Us
 */
export type contactUsPublicContactPostResponse202 = {
  data: unknown;
  status: 202;
};

export type contactUsPublicContactPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type contactUsPublicContactPostResponseSuccess =
  contactUsPublicContactPostResponse202 & {
    headers: Headers;
  };
export type contactUsPublicContactPostResponseError =
  contactUsPublicContactPostResponse422 & {
    headers: Headers;
  };

export type contactUsPublicContactPostResponse =
  | contactUsPublicContactPostResponseSuccess
  | contactUsPublicContactPostResponseError;

export const getContactUsPublicContactPostUrl = () => {
  return `/public/contact`;
};

export const contactUsPublicContactPost = async (
  contactForm: ContactForm,
  options?: RequestInit,
): Promise<contactUsPublicContactPostResponse> => {
  return customFetch<contactUsPublicContactPostResponse>(
    getContactUsPublicContactPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(contactForm),
    },
  );
};

/**
 * @summary Create Strategy Endpoint
 */
export type createStrategyEndpointStrategiesPostResponse200 = {
  data: StrategyResponse;
  status: 200;
};

export type createStrategyEndpointStrategiesPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createStrategyEndpointStrategiesPostResponseSuccess =
  createStrategyEndpointStrategiesPostResponse200 & {
    headers: Headers;
  };
export type createStrategyEndpointStrategiesPostResponseError =
  createStrategyEndpointStrategiesPostResponse422 & {
    headers: Headers;
  };

export type createStrategyEndpointStrategiesPostResponse =
  | createStrategyEndpointStrategiesPostResponseSuccess
  | createStrategyEndpointStrategiesPostResponseError;

export const getCreateStrategyEndpointStrategiesPostUrl = () => {
  return `/strategies/`;
};

export const createStrategyEndpointStrategiesPost = async (
  strategyCreate: StrategyCreate,
  options?: RequestInit,
): Promise<createStrategyEndpointStrategiesPostResponse> => {
  return customFetch<createStrategyEndpointStrategiesPostResponse>(
    getCreateStrategyEndpointStrategiesPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(strategyCreate),
    },
  );
};

/**
 * List all strategies with pagination (without code field).
 * @summary List Strategies Endpoint
 */
export type listStrategiesEndpointStrategiesGetResponse200 = {
  data: StrategyResponse[];
  status: 200;
};

export type listStrategiesEndpointStrategiesGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type listStrategiesEndpointStrategiesGetResponseSuccess =
  listStrategiesEndpointStrategiesGetResponse200 & {
    headers: Headers;
  };
export type listStrategiesEndpointStrategiesGetResponseError =
  listStrategiesEndpointStrategiesGetResponse422 & {
    headers: Headers;
  };

export type listStrategiesEndpointStrategiesGetResponse =
  | listStrategiesEndpointStrategiesGetResponseSuccess
  | listStrategiesEndpointStrategiesGetResponseError;

export const getListStrategiesEndpointStrategiesGetUrl = (
  params?: ListStrategiesEndpointStrategiesGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/strategies/?${stringifiedParams}`
    : `/strategies/`;
};

export const listStrategiesEndpointStrategiesGet = async (
  params?: ListStrategiesEndpointStrategiesGetParams,
  options?: RequestInit,
): Promise<listStrategiesEndpointStrategiesGetResponse> => {
  return customFetch<listStrategiesEndpointStrategiesGetResponse>(
    getListStrategiesEndpointStrategiesGetUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Get a strategy by ID with full details including code.
 * @summary Get Strategy Endpoint
 */
export type getStrategyEndpointStrategiesStrategyIdGetResponse200 = {
  data: StrategyDetailResponse;
  status: 200;
};

export type getStrategyEndpointStrategiesStrategyIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getStrategyEndpointStrategiesStrategyIdGetResponseSuccess =
  getStrategyEndpointStrategiesStrategyIdGetResponse200 & {
    headers: Headers;
  };
export type getStrategyEndpointStrategiesStrategyIdGetResponseError =
  getStrategyEndpointStrategiesStrategyIdGetResponse422 & {
    headers: Headers;
  };

export type getStrategyEndpointStrategiesStrategyIdGetResponse =
  | getStrategyEndpointStrategiesStrategyIdGetResponseSuccess
  | getStrategyEndpointStrategiesStrategyIdGetResponseError;

export const getGetStrategyEndpointStrategiesStrategyIdGetUrl = (
  strategyId: string,
) => {
  return `/strategies/${strategyId}`;
};

export const getStrategyEndpointStrategiesStrategyIdGet = async (
  strategyId: string,
  options?: RequestInit,
): Promise<getStrategyEndpointStrategiesStrategyIdGetResponse> => {
  return customFetch<getStrategyEndpointStrategiesStrategyIdGetResponse>(
    getGetStrategyEndpointStrategiesStrategyIdGetUrl(strategyId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Update a strategy (name and/or description only).
 * @summary Update Strategy Endpoint
 */
export type updateStrategyEndpointStrategiesStrategyIdPatchResponse200 = {
  data: StrategyResponse;
  status: 200;
};

export type updateStrategyEndpointStrategiesStrategyIdPatchResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type updateStrategyEndpointStrategiesStrategyIdPatchResponseSuccess =
  updateStrategyEndpointStrategiesStrategyIdPatchResponse200 & {
    headers: Headers;
  };
export type updateStrategyEndpointStrategiesStrategyIdPatchResponseError =
  updateStrategyEndpointStrategiesStrategyIdPatchResponse422 & {
    headers: Headers;
  };

export type updateStrategyEndpointStrategiesStrategyIdPatchResponse =
  | updateStrategyEndpointStrategiesStrategyIdPatchResponseSuccess
  | updateStrategyEndpointStrategiesStrategyIdPatchResponseError;

export const getUpdateStrategyEndpointStrategiesStrategyIdPatchUrl = (
  strategyId: string,
) => {
  return `/strategies/${strategyId}`;
};

export const updateStrategyEndpointStrategiesStrategyIdPatch = async (
  strategyId: string,
  strategyUpdate: StrategyUpdate,
  options?: RequestInit,
): Promise<updateStrategyEndpointStrategiesStrategyIdPatchResponse> => {
  return customFetch<updateStrategyEndpointStrategiesStrategyIdPatchResponse>(
    getUpdateStrategyEndpointStrategiesStrategyIdPatchUrl(strategyId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(strategyUpdate),
    },
  );
};

/**
 * Delete a strategy.
 * @summary Delete Strategy Endpoint
 */
export type deleteStrategyEndpointStrategiesStrategyIdDeleteResponse204 = {
  data: void;
  status: 204;
};

export type deleteStrategyEndpointStrategiesStrategyIdDeleteResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type deleteStrategyEndpointStrategiesStrategyIdDeleteResponseSuccess =
  deleteStrategyEndpointStrategiesStrategyIdDeleteResponse204 & {
    headers: Headers;
  };
export type deleteStrategyEndpointStrategiesStrategyIdDeleteResponseError =
  deleteStrategyEndpointStrategiesStrategyIdDeleteResponse422 & {
    headers: Headers;
  };

export type deleteStrategyEndpointStrategiesStrategyIdDeleteResponse =
  | deleteStrategyEndpointStrategiesStrategyIdDeleteResponseSuccess
  | deleteStrategyEndpointStrategiesStrategyIdDeleteResponseError;

export const getDeleteStrategyEndpointStrategiesStrategyIdDeleteUrl = (
  strategyId: string,
) => {
  return `/strategies/${strategyId}`;
};

export const deleteStrategyEndpointStrategiesStrategyIdDelete = async (
  strategyId: string,
  options?: RequestInit,
): Promise<deleteStrategyEndpointStrategiesStrategyIdDeleteResponse> => {
  return customFetch<deleteStrategyEndpointStrategiesStrategyIdDeleteResponse>(
    getDeleteStrategyEndpointStrategiesStrategyIdDeleteUrl(strategyId),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * Get a strategy summary with pre-calculated metrics.
 * @summary Get Strategy Summary Endpoint
 */
export type getStrategySummaryEndpointStrategiesStrategyIdSummaryGetResponse200 =
  {
    data: StrategySummaryResponse;
    status: 200;
  };

export type getStrategySummaryEndpointStrategiesStrategyIdSummaryGetResponse422 =
  {
    data: HTTPValidationError;
    status: 422;
  };

export type getStrategySummaryEndpointStrategiesStrategyIdSummaryGetResponseSuccess =
  getStrategySummaryEndpointStrategiesStrategyIdSummaryGetResponse200 & {
    headers: Headers;
  };
export type getStrategySummaryEndpointStrategiesStrategyIdSummaryGetResponseError =
  getStrategySummaryEndpointStrategiesStrategyIdSummaryGetResponse422 & {
    headers: Headers;
  };

export type getStrategySummaryEndpointStrategiesStrategyIdSummaryGetResponse =
  | getStrategySummaryEndpointStrategiesStrategyIdSummaryGetResponseSuccess
  | getStrategySummaryEndpointStrategiesStrategyIdSummaryGetResponseError;

export const getGetStrategySummaryEndpointStrategiesStrategyIdSummaryGetUrl = (
  strategyId: string,
) => {
  return `/strategies/${strategyId}/summary`;
};

export const getStrategySummaryEndpointStrategiesStrategyIdSummaryGet = async (
  strategyId: string,
  options?: RequestInit,
): Promise<getStrategySummaryEndpointStrategiesStrategyIdSummaryGetResponse> => {
  return customFetch<getStrategySummaryEndpointStrategiesStrategyIdSummaryGetResponse>(
    getGetStrategySummaryEndpointStrategiesStrategyIdSummaryGetUrl(strategyId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * List all strategies with pre-calculated metrics summaries.
 * @summary List Strategy Summaries Endpoint
 */
export type listStrategySummariesEndpointStrategiesSummariesGetResponse200 = {
  data: StrategySummaryResponse[];
  status: 200;
};

export type listStrategySummariesEndpointStrategiesSummariesGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type listStrategySummariesEndpointStrategiesSummariesGetResponseSuccess =
  listStrategySummariesEndpointStrategiesSummariesGetResponse200 & {
    headers: Headers;
  };
export type listStrategySummariesEndpointStrategiesSummariesGetResponseError =
  listStrategySummariesEndpointStrategiesSummariesGetResponse422 & {
    headers: Headers;
  };

export type listStrategySummariesEndpointStrategiesSummariesGetResponse =
  | listStrategySummariesEndpointStrategiesSummariesGetResponseSuccess
  | listStrategySummariesEndpointStrategiesSummariesGetResponseError;

export const getListStrategySummariesEndpointStrategiesSummariesGetUrl = (
  params?: ListStrategySummariesEndpointStrategiesSummariesGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/strategies/summaries/?${stringifiedParams}`
    : `/strategies/summaries/`;
};

export const listStrategySummariesEndpointStrategiesSummariesGet = async (
  params?: ListStrategySummariesEndpointStrategiesSummariesGetParams,
  options?: RequestInit,
): Promise<listStrategySummariesEndpointStrategiesSummariesGetResponse> => {
  return customFetch<listStrategySummariesEndpointStrategiesSummariesGetResponse>(
    getListStrategySummariesEndpointStrategiesSummariesGetUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};
