/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { customFetch } from "./lib/custom-fetch";
export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface InstrumentCreate {
  instrument_id: string;
  symbol: string;
  tick_size?: number;
  price?: number;
}

export interface OCOOrderCreate {
  strategy_type: StrategyType;
  instrument_id: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  legs: OrderBase[];
}

export interface Ohlc {
  time: number;
  open: number;
  high: number;
  low: number;
  close: number;
}

export interface OTOCOOrderCreate {
  parent: OrderBase;
  /**
   * @minItems 2
   * @maxItems 2
   */
  oco_legs: OrderBase[];
}

export interface OTOOrderCreate {
  strategy_type: StrategyType;
  instrument_id: string;
  parent: OrderBase;
  child: OrderBase;
}

export type OrderBaseLimitPrice = number | null;

export type OrderBaseStopPrice = number | null;

export interface OrderBase {
  order_id: string;
  user_id: string;
  order_type: OrderType;
  side: Side;
  quantity: number;
  limit_price?: OrderBaseLimitPrice;
  stop_price?: OrderBaseStopPrice;
}

export type OrderModifyLimitPrice = number | null;

export type OrderModifyStopPrice = number | null;

export interface OrderModify {
  limit_price?: OrderModifyLimitPrice;
  stop_price?: OrderModifyStopPrice;
}

export type OrderReadLimitPrice = number | null;

export type OrderReadStopPrice = number | null;

export type OrderReadAvgFillPrice = number | null;

export interface OrderRead {
  order_id: string;
  order_type: OrderType;
  side: Side;
  quantity: number;
  limit_price?: OrderReadLimitPrice;
  stop_price?: OrderReadStopPrice;
  strategy_type: StrategyType;
  status: OrderStatus;
  executed_quantity: number;
  avg_fill_price?: OrderReadAvgFillPrice;
  created_at: string;
}

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderStatus = {
  pending: "pending",
  placed: "placed",
  partially_filled: "partially_filled",
  filled: "filled",
  cancelled: "cancelled",
} as const;

export type OrderType = (typeof OrderType)[keyof typeof OrderType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderType = {
  market: "market",
  limit: "limit",
  stop: "stop",
} as const;

export interface PaginatedResponseOrderRead {
  page: number;
  size: number;
  has_next: boolean;
  data: OrderRead[];
}

export interface PortfolioHistory {
  time: string;
  value: number;
}

export type Side = (typeof Side)[keyof typeof Side];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Side = {
  bid: "bid",
  ask: "ask",
} as const;

export type SingleOrderCreateLimitPrice = number | null;

export type SingleOrderCreateStopPrice = number | null;

export interface SingleOrderCreate {
  order_id: string;
  user_id: string;
  order_type: OrderType;
  side: Side;
  quantity: number;
  limit_price?: SingleOrderCreateLimitPrice;
  stop_price?: SingleOrderCreateStopPrice;
  strategy_type: StrategyType;
  instrument_id: string;
}

export type Stats24hPrice = number | null;

export interface Stats24h {
  price: Stats24hPrice;
  h24_volume: number;
  h24_change: number;
  h24_high: number;
  h24_low: number;
}

export type StrategyType = (typeof StrategyType)[keyof typeof StrategyType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StrategyType = {
  single: "single",
  oco: "oco",
  oto: "oto",
  otoco: "otoco",
} as const;

export type TimeFrame = (typeof TimeFrame)[keyof typeof TimeFrame];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TimeFrame = {
  "5m": "5m",
  "15m": "15m",
  "1h": "1h",
  "4h": "4h",
  "1d": "1d",
} as const;

export interface UserCreate {
  username: string;
  email: string;
  password: string;
}

export type UserLoginUsername = string | null;

export type UserLoginEmail = string | null;

export interface UserLogin {
  username?: UserLoginUsername;
  email?: UserLoginEmail;
  password: string;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type GetInstrumentsInstrumentsGetParams = {
  instrument_id?: string | null;
};

export type GetInstrumentOhlcInstrumentsInstrumentIdOhlcGetParams = {
  timeframe: TimeFrame;
};

export type GetRecentTradesInstrumentsInstrumentIdTradesGetParams = {
  /**
   * @minimum 1
   */
  page?: number;
};

export type GetOrdersOrdersGetParams = {
  /**
   * @minimum 1
   */
  page?: number;
  instrument?: string[];
  status?: OrderStatus[];
  side?: Side[];
};

export type GetUserOverviewUserGetParams = {
  /**
   * @minimum 1
   */
  page?: number;
};

export type GetUserPortfolioHistoryUserHistoryGetParams = {
  interval: GetUserPortfolioHistoryUserHistoryGetInterval;
};

export type GetUserPortfolioHistoryUserHistoryGetInterval =
  (typeof GetUserPortfolioHistoryUserHistoryGetInterval)[keyof typeof GetUserPortfolioHistoryUserHistoryGetInterval];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUserPortfolioHistoryUserHistoryGetInterval = {
  "1d": "1d",
  "1w": "1w",
  "1m": "1m",
  "3m": "3m",
  "6m": "6m",
  "1y": "1y",
} as const;

/**
 * @summary Login User
 */
export type loginUserAuthLoginPostResponse200 = {
  data: unknown;
  status: 200;
};

export type loginUserAuthLoginPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type loginUserAuthLoginPostResponseSuccess =
  loginUserAuthLoginPostResponse200 & {
    headers: Headers;
  };
export type loginUserAuthLoginPostResponseError =
  loginUserAuthLoginPostResponse422 & {
    headers: Headers;
  };

export type loginUserAuthLoginPostResponse =
  | loginUserAuthLoginPostResponseSuccess
  | loginUserAuthLoginPostResponseError;

export const getLoginUserAuthLoginPostUrl = () => {
  return `/auth/login`;
};

export const loginUserAuthLoginPost = async (
  userLogin: UserLogin,
  options?: RequestInit,
): Promise<loginUserAuthLoginPostResponse> => {
  return customFetch<loginUserAuthLoginPostResponse>(
    getLoginUserAuthLoginPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(userLogin),
    },
  );
};

/**
 * @summary Register User
 */
export type registerUserAuthRegisterPostResponse200 = {
  data: unknown;
  status: 200;
};

export type registerUserAuthRegisterPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type registerUserAuthRegisterPostResponseSuccess =
  registerUserAuthRegisterPostResponse200 & {
    headers: Headers;
  };
export type registerUserAuthRegisterPostResponseError =
  registerUserAuthRegisterPostResponse422 & {
    headers: Headers;
  };

export type registerUserAuthRegisterPostResponse =
  | registerUserAuthRegisterPostResponseSuccess
  | registerUserAuthRegisterPostResponseError;

export const getRegisterUserAuthRegisterPostUrl = () => {
  return `/auth/register`;
};

export const registerUserAuthRegisterPost = async (
  userCreate: UserCreate,
  options?: RequestInit,
): Promise<registerUserAuthRegisterPostResponse> => {
  return customFetch<registerUserAuthRegisterPostResponse>(
    getRegisterUserAuthRegisterPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(userCreate),
    },
  );
};

/**
 * @summary Get Current User
 */
export type getCurrentUserAuthMeGetResponse200 = {
  data: unknown;
  status: 200;
};

export type getCurrentUserAuthMeGetResponseSuccess =
  getCurrentUserAuthMeGetResponse200 & {
    headers: Headers;
  };
export type getCurrentUserAuthMeGetResponse =
  getCurrentUserAuthMeGetResponseSuccess;

export const getGetCurrentUserAuthMeGetUrl = () => {
  return `/auth/me`;
};

export const getCurrentUserAuthMeGet = async (
  options?: RequestInit,
): Promise<getCurrentUserAuthMeGetResponse> => {
  return customFetch<getCurrentUserAuthMeGetResponse>(
    getGetCurrentUserAuthMeGetUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Creates a new tradeable instrument.
 * @summary Create Instrument
 */
export type createInstrumentInstrumentsPostResponse201 = {
  data: unknown;
  status: 201;
};

export type createInstrumentInstrumentsPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createInstrumentInstrumentsPostResponseSuccess =
  createInstrumentInstrumentsPostResponse201 & {
    headers: Headers;
  };
export type createInstrumentInstrumentsPostResponseError =
  createInstrumentInstrumentsPostResponse422 & {
    headers: Headers;
  };

export type createInstrumentInstrumentsPostResponse =
  | createInstrumentInstrumentsPostResponseSuccess
  | createInstrumentInstrumentsPostResponseError;

export const getCreateInstrumentInstrumentsPostUrl = () => {
  return `/instruments/`;
};

export const createInstrumentInstrumentsPost = async (
  instrumentCreate: InstrumentCreate,
  options?: RequestInit,
): Promise<createInstrumentInstrumentsPostResponse> => {
  return customFetch<createInstrumentInstrumentsPostResponse>(
    getCreateInstrumentInstrumentsPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(instrumentCreate),
    },
  );
};

/**
 * @summary Get Instruments
 */
export type getInstrumentsInstrumentsGetResponse200 = {
  data: unknown;
  status: 200;
};

export type getInstrumentsInstrumentsGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getInstrumentsInstrumentsGetResponseSuccess =
  getInstrumentsInstrumentsGetResponse200 & {
    headers: Headers;
  };
export type getInstrumentsInstrumentsGetResponseError =
  getInstrumentsInstrumentsGetResponse422 & {
    headers: Headers;
  };

export type getInstrumentsInstrumentsGetResponse =
  | getInstrumentsInstrumentsGetResponseSuccess
  | getInstrumentsInstrumentsGetResponseError;

export const getGetInstrumentsInstrumentsGetUrl = (
  params?: GetInstrumentsInstrumentsGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/instruments/?${stringifiedParams}`
    : `/instruments/`;
};

export const getInstrumentsInstrumentsGet = async (
  params?: GetInstrumentsInstrumentsGetParams,
  options?: RequestInit,
): Promise<getInstrumentsInstrumentsGetResponse> => {
  return customFetch<getInstrumentsInstrumentsGetResponse>(
    getGetInstrumentsInstrumentsGetUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Retrieves Open-High-Low-Close (OHLC) data for a given instrument.
Requires TimescaleDB with the timescale_toolkit extension for `time_bucket`,
`first`, and `last` functions.
 * @summary Get Instrument Ohlc
 */
export type getInstrumentOhlcInstrumentsInstrumentIdOhlcGetResponse200 = {
  data: Ohlc[];
  status: 200;
};

export type getInstrumentOhlcInstrumentsInstrumentIdOhlcGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getInstrumentOhlcInstrumentsInstrumentIdOhlcGetResponseSuccess =
  getInstrumentOhlcInstrumentsInstrumentIdOhlcGetResponse200 & {
    headers: Headers;
  };
export type getInstrumentOhlcInstrumentsInstrumentIdOhlcGetResponseError =
  getInstrumentOhlcInstrumentsInstrumentIdOhlcGetResponse422 & {
    headers: Headers;
  };

export type getInstrumentOhlcInstrumentsInstrumentIdOhlcGetResponse =
  | getInstrumentOhlcInstrumentsInstrumentIdOhlcGetResponseSuccess
  | getInstrumentOhlcInstrumentsInstrumentIdOhlcGetResponseError;

export const getGetInstrumentOhlcInstrumentsInstrumentIdOhlcGetUrl = (
  instrumentId: string,
  params: GetInstrumentOhlcInstrumentsInstrumentIdOhlcGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/instruments/${instrumentId}/ohlc?${stringifiedParams}`
    : `/instruments/${instrumentId}/ohlc`;
};

export const getInstrumentOhlcInstrumentsInstrumentIdOhlcGet = async (
  instrumentId: string,
  params: GetInstrumentOhlcInstrumentsInstrumentIdOhlcGetParams,
  options?: RequestInit,
): Promise<getInstrumentOhlcInstrumentsInstrumentIdOhlcGetResponse> => {
  return customFetch<getInstrumentOhlcInstrumentsInstrumentIdOhlcGetResponse>(
    getGetInstrumentOhlcInstrumentsInstrumentIdOhlcGetUrl(instrumentId, params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get Instrument 24H Stats
 */
export type getInstrument24hStatsInstrumentsInstrumentId24hGetResponse200 = {
  data: Stats24h;
  status: 200;
};

export type getInstrument24hStatsInstrumentsInstrumentId24hGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getInstrument24hStatsInstrumentsInstrumentId24hGetResponseSuccess =
  getInstrument24hStatsInstrumentsInstrumentId24hGetResponse200 & {
    headers: Headers;
  };
export type getInstrument24hStatsInstrumentsInstrumentId24hGetResponseError =
  getInstrument24hStatsInstrumentsInstrumentId24hGetResponse422 & {
    headers: Headers;
  };

export type getInstrument24hStatsInstrumentsInstrumentId24hGetResponse =
  | getInstrument24hStatsInstrumentsInstrumentId24hGetResponseSuccess
  | getInstrument24hStatsInstrumentsInstrumentId24hGetResponseError;

export const getGetInstrument24hStatsInstrumentsInstrumentId24hGetUrl = (
  instrumentId: string,
) => {
  return `/instruments/${instrumentId}/24h`;
};

export const getInstrument24hStatsInstrumentsInstrumentId24hGet = async (
  instrumentId: string,
  options?: RequestInit,
): Promise<getInstrument24hStatsInstrumentsInstrumentId24hGetResponse> => {
  return customFetch<getInstrument24hStatsInstrumentsInstrumentId24hGetResponse>(
    getGetInstrument24hStatsInstrumentsInstrumentId24hGetUrl(instrumentId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get Recent Trades
 */
export type getRecentTradesInstrumentsInstrumentIdTradesGetResponse200 = {
  data: unknown;
  status: 200;
};

export type getRecentTradesInstrumentsInstrumentIdTradesGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getRecentTradesInstrumentsInstrumentIdTradesGetResponseSuccess =
  getRecentTradesInstrumentsInstrumentIdTradesGetResponse200 & {
    headers: Headers;
  };
export type getRecentTradesInstrumentsInstrumentIdTradesGetResponseError =
  getRecentTradesInstrumentsInstrumentIdTradesGetResponse422 & {
    headers: Headers;
  };

export type getRecentTradesInstrumentsInstrumentIdTradesGetResponse =
  | getRecentTradesInstrumentsInstrumentIdTradesGetResponseSuccess
  | getRecentTradesInstrumentsInstrumentIdTradesGetResponseError;

export const getGetRecentTradesInstrumentsInstrumentIdTradesGetUrl = (
  instrumentId: string,
  params?: GetRecentTradesInstrumentsInstrumentIdTradesGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/instruments/${instrumentId}/trades?${stringifiedParams}`
    : `/instruments/${instrumentId}/trades`;
};

export const getRecentTradesInstrumentsInstrumentIdTradesGet = async (
  instrumentId: string,
  params?: GetRecentTradesInstrumentsInstrumentIdTradesGetParams,
  options?: RequestInit,
): Promise<getRecentTradesInstrumentsInstrumentIdTradesGetResponse> => {
  return customFetch<getRecentTradesInstrumentsInstrumentIdTradesGetResponse>(
    getGetRecentTradesInstrumentsInstrumentIdTradesGetUrl(instrumentId, params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Accepts a new single order.
 * @summary Create Order
 */
export type createOrderOrdersPostResponse202 = {
  data: unknown;
  status: 202;
};

export type createOrderOrdersPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createOrderOrdersPostResponseSuccess =
  createOrderOrdersPostResponse202 & {
    headers: Headers;
  };
export type createOrderOrdersPostResponseError =
  createOrderOrdersPostResponse422 & {
    headers: Headers;
  };

export type createOrderOrdersPostResponse =
  | createOrderOrdersPostResponseSuccess
  | createOrderOrdersPostResponseError;

export const getCreateOrderOrdersPostUrl = () => {
  return `/orders/`;
};

export const createOrderOrdersPost = async (
  singleOrderCreate: SingleOrderCreate,
  options?: RequestInit,
): Promise<createOrderOrdersPostResponse> => {
  return customFetch<createOrderOrdersPostResponse>(
    getCreateOrderOrdersPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(singleOrderCreate),
    },
  );
};

/**
 * Retrieves a paginated list of orders for the authenticated user,
with optional filtering.
 * @summary Get Orders
 */
export type getOrdersOrdersGetResponse200 = {
  data: PaginatedResponseOrderRead;
  status: 200;
};

export type getOrdersOrdersGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getOrdersOrdersGetResponseSuccess =
  getOrdersOrdersGetResponse200 & {
    headers: Headers;
  };
export type getOrdersOrdersGetResponseError = getOrdersOrdersGetResponse422 & {
  headers: Headers;
};

export type getOrdersOrdersGetResponse =
  | getOrdersOrdersGetResponseSuccess
  | getOrdersOrdersGetResponseError;

export const getGetOrdersOrdersGetUrl = (params?: GetOrdersOrdersGetParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["instrument", "status", "side"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? "null" : v.toString());
      });
      return;
    }

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/orders/?${stringifiedParams}`
    : `/orders/`;
};

export const getOrdersOrdersGet = async (
  params?: GetOrdersOrdersGetParams,
  options?: RequestInit,
): Promise<getOrdersOrdersGetResponse> => {
  return customFetch<getOrdersOrdersGetResponse>(
    getGetOrdersOrdersGetUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Sends requests to cancel all PENDING or PARTIALLY_FILLED orders.
 * @summary Cancel all active orders for the user
 */
export type cancelAllOrdersOrdersDeleteResponse202 = {
  data: unknown;
  status: 202;
};

export type cancelAllOrdersOrdersDeleteResponseSuccess =
  cancelAllOrdersOrdersDeleteResponse202 & {
    headers: Headers;
  };
export type cancelAllOrdersOrdersDeleteResponse =
  cancelAllOrdersOrdersDeleteResponseSuccess;

export const getCancelAllOrdersOrdersDeleteUrl = () => {
  return `/orders/`;
};

export const cancelAllOrdersOrdersDelete = async (
  options?: RequestInit,
): Promise<cancelAllOrdersOrdersDeleteResponse> => {
  return customFetch<cancelAllOrdersOrdersDeleteResponse>(
    getCancelAllOrdersOrdersDeleteUrl(),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * Accepts a new OCO (One-Cancels-the-Other) order group.
 * @summary Create Oco Order
 */
export type createOcoOrderOrdersOcoPostResponse202 = {
  data: unknown;
  status: 202;
};

export type createOcoOrderOrdersOcoPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createOcoOrderOrdersOcoPostResponseSuccess =
  createOcoOrderOrdersOcoPostResponse202 & {
    headers: Headers;
  };
export type createOcoOrderOrdersOcoPostResponseError =
  createOcoOrderOrdersOcoPostResponse422 & {
    headers: Headers;
  };

export type createOcoOrderOrdersOcoPostResponse =
  | createOcoOrderOrdersOcoPostResponseSuccess
  | createOcoOrderOrdersOcoPostResponseError;

export const getCreateOcoOrderOrdersOcoPostUrl = () => {
  return `/orders/oco`;
};

export const createOcoOrderOrdersOcoPost = async (
  oCOOrderCreate: OCOOrderCreate,
  options?: RequestInit,
): Promise<createOcoOrderOrdersOcoPostResponse> => {
  return customFetch<createOcoOrderOrdersOcoPostResponse>(
    getCreateOcoOrderOrdersOcoPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(oCOOrderCreate),
    },
  );
};

/**
 * Accepts a new OTO (One-Triggers-the-Other) order group.
 * @summary Create Oto Order
 */
export type createOtoOrderOrdersOtoPostResponse202 = {
  data: unknown;
  status: 202;
};

export type createOtoOrderOrdersOtoPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createOtoOrderOrdersOtoPostResponseSuccess =
  createOtoOrderOrdersOtoPostResponse202 & {
    headers: Headers;
  };
export type createOtoOrderOrdersOtoPostResponseError =
  createOtoOrderOrdersOtoPostResponse422 & {
    headers: Headers;
  };

export type createOtoOrderOrdersOtoPostResponse =
  | createOtoOrderOrdersOtoPostResponseSuccess
  | createOtoOrderOrdersOtoPostResponseError;

export const getCreateOtoOrderOrdersOtoPostUrl = () => {
  return `/orders/oto`;
};

export const createOtoOrderOrdersOtoPost = async (
  oTOOrderCreate: OTOOrderCreate,
  options?: RequestInit,
): Promise<createOtoOrderOrdersOtoPostResponse> => {
  return customFetch<createOtoOrderOrdersOtoPostResponse>(
    getCreateOtoOrderOrdersOtoPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(oTOOrderCreate),
    },
  );
};

/**
 * Accepts a new OTOCO (One-Triggers-One-Cancels-the-Other) order group.
 * @summary Create Otoco Order
 */
export type createOtocoOrderOrdersOtocoPostResponse202 = {
  data: unknown;
  status: 202;
};

export type createOtocoOrderOrdersOtocoPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createOtocoOrderOrdersOtocoPostResponseSuccess =
  createOtocoOrderOrdersOtocoPostResponse202 & {
    headers: Headers;
  };
export type createOtocoOrderOrdersOtocoPostResponseError =
  createOtocoOrderOrdersOtocoPostResponse422 & {
    headers: Headers;
  };

export type createOtocoOrderOrdersOtocoPostResponse =
  | createOtocoOrderOrdersOtocoPostResponseSuccess
  | createOtocoOrderOrdersOtocoPostResponseError;

export const getCreateOtocoOrderOrdersOtocoPostUrl = () => {
  return `/orders/otoco`;
};

export const createOtocoOrderOrdersOtocoPost = async (
  oTOCOOrderCreate: OTOCOOrderCreate,
  options?: RequestInit,
): Promise<createOtocoOrderOrdersOtocoPostResponse> => {
  return customFetch<createOtocoOrderOrdersOtocoPostResponse>(
    getCreateOtocoOrderOrdersOtocoPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(oTOCOOrderCreate),
    },
  );
};

/**
 * Retrieves a single order by its ID.
 * @summary Get Order
 */
export type getOrderOrdersOrderIdGetResponse200 = {
  data: OrderRead;
  status: 200;
};

export type getOrderOrdersOrderIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getOrderOrdersOrderIdGetResponseSuccess =
  getOrderOrdersOrderIdGetResponse200 & {
    headers: Headers;
  };
export type getOrderOrdersOrderIdGetResponseError =
  getOrderOrdersOrderIdGetResponse422 & {
    headers: Headers;
  };

export type getOrderOrdersOrderIdGetResponse =
  | getOrderOrdersOrderIdGetResponseSuccess
  | getOrderOrdersOrderIdGetResponseError;

export const getGetOrderOrdersOrderIdGetUrl = (orderId: string) => {
  return `/orders/${orderId}`;
};

export const getOrderOrdersOrderIdGet = async (
  orderId: string,
  options?: RequestInit,
): Promise<getOrderOrdersOrderIdGetResponse> => {
  return customFetch<getOrderOrdersOrderIdGetResponse>(
    getGetOrderOrdersOrderIdGetUrl(orderId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Requests modification of an active order (e.g., changing the price).
 * @summary Modify an active order
 */
export type modifyOrderOrdersOrderIdPatchResponse202 = {
  data: unknown;
  status: 202;
};

export type modifyOrderOrdersOrderIdPatchResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type modifyOrderOrdersOrderIdPatchResponseSuccess =
  modifyOrderOrdersOrderIdPatchResponse202 & {
    headers: Headers;
  };
export type modifyOrderOrdersOrderIdPatchResponseError =
  modifyOrderOrdersOrderIdPatchResponse422 & {
    headers: Headers;
  };

export type modifyOrderOrdersOrderIdPatchResponse =
  | modifyOrderOrdersOrderIdPatchResponseSuccess
  | modifyOrderOrdersOrderIdPatchResponseError;

export const getModifyOrderOrdersOrderIdPatchUrl = (orderId: string) => {
  return `/orders/${orderId}`;
};

export const modifyOrderOrdersOrderIdPatch = async (
  orderId: string,
  orderModify: OrderModify,
  options?: RequestInit,
): Promise<modifyOrderOrdersOrderIdPatchResponse> => {
  return customFetch<modifyOrderOrdersOrderIdPatchResponse>(
    getModifyOrderOrdersOrderIdPatchUrl(orderId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(orderModify),
    },
  );
};

/**
 * Sends a request to cancel a specific order by its ID.
 * @summary Cancel a specific order
 */
export type cancelOrderOrdersOrderIdDeleteResponse202 = {
  data: unknown;
  status: 202;
};

export type cancelOrderOrdersOrderIdDeleteResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type cancelOrderOrdersOrderIdDeleteResponseSuccess =
  cancelOrderOrdersOrderIdDeleteResponse202 & {
    headers: Headers;
  };
export type cancelOrderOrdersOrderIdDeleteResponseError =
  cancelOrderOrdersOrderIdDeleteResponse422 & {
    headers: Headers;
  };

export type cancelOrderOrdersOrderIdDeleteResponse =
  | cancelOrderOrdersOrderIdDeleteResponseSuccess
  | cancelOrderOrdersOrderIdDeleteResponseError;

export const getCancelOrderOrdersOrderIdDeleteUrl = (orderId: string) => {
  return `/orders/${orderId}`;
};

export const cancelOrderOrdersOrderIdDelete = async (
  orderId: string,
  options?: RequestInit,
): Promise<cancelOrderOrdersOrderIdDeleteResponse> => {
  return customFetch<cancelOrderOrdersOrderIdDeleteResponse>(
    getCancelOrderOrdersOrderIdDeleteUrl(orderId),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Healthcheck
 */
export type healthcheckPublicHealthcheckGetResponse200 = {
  data: unknown;
  status: 200;
};

export type healthcheckPublicHealthcheckGetResponseSuccess =
  healthcheckPublicHealthcheckGetResponse200 & {
    headers: Headers;
  };
export type healthcheckPublicHealthcheckGetResponse =
  healthcheckPublicHealthcheckGetResponseSuccess;

export const getHealthcheckPublicHealthcheckGetUrl = () => {
  return `/public/healthcheck`;
};

export const healthcheckPublicHealthcheckGet = async (
  options?: RequestInit,
): Promise<healthcheckPublicHealthcheckGetResponse> => {
  return customFetch<healthcheckPublicHealthcheckGetResponse>(
    getHealthcheckPublicHealthcheckGetUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get User Overview
 */
export type getUserOverviewUserGetResponse200 = {
  data: unknown;
  status: 200;
};

export type getUserOverviewUserGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getUserOverviewUserGetResponseSuccess =
  getUserOverviewUserGetResponse200 & {
    headers: Headers;
  };
export type getUserOverviewUserGetResponseError =
  getUserOverviewUserGetResponse422 & {
    headers: Headers;
  };

export type getUserOverviewUserGetResponse =
  | getUserOverviewUserGetResponseSuccess
  | getUserOverviewUserGetResponseError;

export const getGetUserOverviewUserGetUrl = (
  params?: GetUserOverviewUserGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/user/?${stringifiedParams}`
    : `/user/`;
};

export const getUserOverviewUserGet = async (
  params?: GetUserOverviewUserGetParams,
  options?: RequestInit,
): Promise<getUserOverviewUserGetResponse> => {
  return customFetch<getUserOverviewUserGetResponse>(
    getGetUserOverviewUserGetUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get User Portfolio History
 */
export type getUserPortfolioHistoryUserHistoryGetResponse200 = {
  data: PortfolioHistory[];
  status: 200;
};

export type getUserPortfolioHistoryUserHistoryGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getUserPortfolioHistoryUserHistoryGetResponseSuccess =
  getUserPortfolioHistoryUserHistoryGetResponse200 & {
    headers: Headers;
  };
export type getUserPortfolioHistoryUserHistoryGetResponseError =
  getUserPortfolioHistoryUserHistoryGetResponse422 & {
    headers: Headers;
  };

export type getUserPortfolioHistoryUserHistoryGetResponse =
  | getUserPortfolioHistoryUserHistoryGetResponseSuccess
  | getUserPortfolioHistoryUserHistoryGetResponseError;

export const getGetUserPortfolioHistoryUserHistoryGetUrl = (
  params: GetUserPortfolioHistoryUserHistoryGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/user/history?${stringifiedParams}`
    : `/user/history`;
};

export const getUserPortfolioHistoryUserHistoryGet = async (
  params: GetUserPortfolioHistoryUserHistoryGetParams,
  options?: RequestInit,
): Promise<getUserPortfolioHistoryUserHistoryGetResponse> => {
  return customFetch<getUserPortfolioHistoryUserHistoryGetResponse>(
    getGetUserPortfolioHistoryUserHistoryGetUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};
